# -*- coding: utf-8 -*-
"""Air_Tracker-Flight_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pga_Tl9NXkOqYz-3qahaoguCtxXWF4C

#**Air Tracker - Flight Analytics**

**Technologies Used:**
```
- Python scripting
- API Data Collection (AeroDataBox)
- SQLite Database Management
- SQL Analytics (11 Complex Queries)
- Streamlit Dashboard
```

Domain : **Aviation/Data Analytics**
by Rajaguru Seethamalai

#PHASE 1: Data Collection API

##Import Libraries
"""

#Import Libraries which are required for the project
import time
import requests
import json
import pandas as pd
from datetime import datetime, timedelta
import sqlite3

print("Libraries imported!")

"""##API Configuration - Test"""

# Test API request
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/iata/IXM"

headers = {
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
  "x-rapidapi-key": "xxxx"
}

response = requests.get(url, headers=headers)

print(response.json())

"""##Fetch Airport Data

###Configure API to fetch 12 Airports
For this project selected 12 airports:
*   Small Indian airports: IXM (Madurai), COK (Kochi)
*   Medium Indian airports: AMD (Ahmedabad), JAI (Jaipur), PNQ (Pune)
*   Major Indian hubs: DEL (Delhi), BOM (Mumbai), BLR (Bangalore), HYD (Hyderabad), MAA (Chennai)
*   International hubs: DXB (Dubai), LHR (London)
"""

# My API credentials

API_HOST = "aerodatabox.p.rapidapi.com"
API_KEY = "xxx"

headers = {
    'x-rapidapi-host': API_HOST,
    'x-rapidapi-key': API_KEY
}

# 12 Airports airports which I have chosen
my_airports = ["IXM", "COK", "AMD", "JAI", "DEL", "BOM", "BLR", "HYD", "MAA", "PNQ", "DXB", "LHR"]

print("API configured")

"""### Fetch Airports Data

### Make function to fetch airports
"""

#Function to fetch airport
def fetch_airport(iata_code):
  url = f"https://{API_HOST}/airports/iata/{iata_code}"
  try:
    response = requests.get(url, headers=headers, timeout=10)
    response.raise_for_status()
    time.sleep(1.2)
    return response.json()
  except Exception as e:
    print(f"Error fetching airport data for {iata_code}: {e}")
    return None

print("fetch_airport() function created")

"""###Fetching Airports Data"""

# Fetch all airports with fetch_airport() function

airport_list = []

for idx, airport in enumerate(my_airports, start=1):
  print(f"Airport {idx}/{len(my_airports)}: {airport}")
  airport_data = fetch_airport(airport)
  if airport_data:
    airport_list.append(airport_data)
    print(f"  {airport} fetched")
  else:
    print(f"Failed to fetch data for airport: {airport}")

print("All airports fetched:")
print(airport_list)

"""### Make a clean Airport DataFrame"""

# Clean & Extract the important details

cleaned_airport_data = []

for airport in airport_list:
  icao_code = airport.get('icao', None)
  iata_code = airport.get('iata', None)
  name = airport.get('shortName', None) or airport.get('fullName', None)
  city = airport.get('municipalityName', None)
  country = airport.get('country', None).get('name', None)
  continent = airport.get('continent', None).get('name', None)
  latitude = airport.get('location', None).get('lat', None)
  longitude = airport.get('location', None).get('lon', None)
  timezone = airport.get('timeZone', None)

  cleaned_airport_data.append((icao_code, iata_code, name, city, country, continent, latitude, longitude, timezone))

df_airports = pd.DataFrame(cleaned_airport_data, columns=['icao_code', 'iata_code', 'name', 'city', 'country', 'continent', 'latitude', 'longitude', 'timezone'])
df_airports

"""### SAVE & RESTORE
>instead of API call

"""

# Saved & Loaded the cleaned flights csv to avoid API calls
df_airports = pd.read_csv("df_airport.csv")
df_airports

"""##Fetch Flights Data
```
   1) Defines a reusable function to call AeroDataBox for airports
   2) Loops over your 12 airports and collects raw JSON
   3) Cleans the JSON into a neat df_airports table
```

###Make Function to fetch flights
fetching all flights at 12 airports for the last 3 days

```
12 hour window:
The API has a limit: Maximum 12 hours per request!
Morning window: 00:00 to 12:00
Evening window: 12:00 to 23:59
```
"""

#Function: fetch one airport by IATA
#FIDS: Airport departures and arrivals (by time range)

def fetch_flights(iata_code, start_date_time, end_date_time):
  url = f"https://{API_HOST}/flights/airports/iata/{iata_code}/{start_date_time}/{end_date_time}"
  querystring = {"withLeg":"true","direction":"Both","withCancelled":"true","withCodeshared":"true","withCargo":"true","withPrivate":"true","withLocation":"false"}
  try:
    response = requests.get(url, headers=headers, params=querystring, timeout=10)
    response.raise_for_status()
    time.sleep(1.2)
    return response.json()
  except Exception as e:
    print(f"Error fetching flights data for {iata_code} {start_date_time}→{end_date_time}: {e}")
    return None

print("fetch_flights() function created")

"""###Time-window generator

"""

#Create 12-hour time windows for the last 3 full days
"""
    Make 2 windows per day:
      - 00:00 → 12:00  (morning)
      - 12:00 → 23:59  (evening)
    Returns a list of dicts with 'date', 'from', 'to', 'label'.
"""

def generate_time_windows(days_back=3):
  time_windows = []

  for day in range(days_back):
    date = datetime.now() - timedelta(days=day+1)
    date_str = date.strftime("%Y-%m-%d")
    print(date_str)
    morning_from = f"{date_str}T00:00"
    morning_to = f"{date_str}T12:00"
    evening_from = f"{date_str}T12:00"
    evening_to = f"{date_str}T23:59"
    time_windows.extend([
        {"date": date_str, "from": morning_from, "to": morning_to, "label": "Morning"},
        {"date": date_str, "from": evening_from, "to": evening_to, "label": "Evening"}
    ])

  return time_windows
windows = generate_time_windows()
print(windows)
for w in windows:
    print(f"  {w['date']} {w['label']}: {w['from']} → {w['to']}")

print("generate_time_windows() function created")

"""###API loop: airports x windows

"""

#Make sure my_airports, fetch_flights, windows are already defined

all_flights_list = []
api_calls = 0
errors = 0

for idx, airport in enumerate(my_airports, start=1):
  print(f"Airport {idx}/{len(my_airports)}: {airport}")
  flights_total = 0

  for w in windows:
    print(f"  {w['date']} {w['label']}: {w['from']} → {w['to']}")

    flights_data = fetch_flights(airport, w['from'], w['to'])
    api_calls += 1

    if flights_data:
      departures = flights_data.get('departures',[]) or []
      arrivals = flights_data.get('arrivals',[]) or []

      count_here = len(departures) + len(arrivals)
      print(f"    {count_here} flights")

      all_flights_list.extend(departures)
      all_flights_list.extend(arrivals)

      flights_total += count_here
      if count_here > 0:
        print(f"    {count_here} flights added")
    else:
      print(f"  Error fetching flights data for {airport} {w['from']}→{w['to']}")
      errors += 1

  print(f" {airport}: {flights_total} flights")

print(f"API calls: {api_calls}")
print(f"Errors: {errors}")

"""### SAVE & RESTORE
>instead of API call
"""

#Temprory restore from raw json
all_flights_list = json.load(open('raw_flights.json', 'r'))

"""###Make a Clean flights into a DataFrame


"""

# all_flights_list: list of raw flight JSON objects from your API loop

cleaned_flights_data = []

#Remove z end of all the time in UTC
def clean_time(s):
  if not isinstance(s, str) or not s.strip():
    return None
  s = s.replace('Z', '')
  return datetime.strptime(s, '%Y-%m-%d %H:%M')

#Delay calculating
def delay_minutes(actual, scheduled):
    if not actual or not scheduled:
        return None
    return (actual - scheduled).total_seconds() / 60

for flight in all_flights_list:
  # Extract from the Nested blocks first
  aircraft = flight.get('aircraft', {}) or {}
  airline = flight.get('airline', {}) or {}
  dep = flight.get('departure', {}) or {}
  arr = flight.get('arrival', {}) or {}


  #Extract from departure Nest
  #Time
  scheduled_dep = clean_time(dep.get('scheduledTime', {}).get('utc', None))
  actual_dep = clean_time(dep.get('revisedTime', {}).get('utc', None))
  #Origin airport
  origin_iata = dep.get('airport', {}).get('iata', None)
  origin_icao = dep.get('airport', {}).get('icao', None)

  #Extract from arrival Nest
  #Time
  scheduled_arr = clean_time(arr.get('scheduledTime', {}).get('utc', None))
  actual_arr = clean_time(arr.get('revisedTime', {}).get('utc', None))
  #Destination airport
  dest_iata = arr.get('airport', {}).get('iata', None)
  dest_icao = arr.get('airport', {}).get('icao', None)

  delay_dep = delay_minutes(actual_dep, scheduled_dep)
  delay_arr = delay_minutes(actual_arr, scheduled_arr)

  #Extrace Aircraft details
  aircraft_reg = aircraft.get('reg')
  aircraft_model = aircraft.get('model')
  aircraft_modes = aircraft.get('modeS')

  #Extract Airline details
  airline_code = airline.get('iata')
  airline_name = airline.get('name')
  airline_icao = airline.get('icao')

  #Extract Flight details
  flight_id = flight.get('number')
  flight_number = flight.get('number', '').split(' ')[-1]
  status = flight.get('status')
  is_cargo = bool(flight.get('isCargo', False))
  is_canceled = flight.get('status') in ['Canceled', 'CanceledUncertain']

  #Append to list

  cleaned_flights_data.append((flight_id, flight_number, airline_code, airline_name,
    aircraft_reg, aircraft_model,
    origin_iata, origin_icao, dest_iata, dest_icao,
    scheduled_arr, actual_arr, delay_arr, scheduled_dep, actual_dep, delay_dep,
    status, is_cargo, is_canceled
  ))

df_flights = pd.DataFrame(cleaned_flights_data,
                          columns=['flight_id', 'flight_number', 'airline_code', 'airline_name',
                                   'aircraft_reg', 'aircraft_model',
                                   'origin_iata','origin_icao','dest_iata','dest_icao',
                                   'scheduled_arr', 'actual_arr','delay_arr', 'scheduled_dep', 'actual_dep','delay_dep',
                                   'status', 'is_cargo', 'is_canceled'])
df_flights.head(20)

df_flights.info()

"""##Fetch Aircraft Data

```
Aircraft_registration check
```






"""

# unique aircraft seen in your flights data
df_aircraft = (df_flights[['aircraft_reg']].drop_duplicates())
df_aircraft.describe()

"""### Collecting Models

```
2300+ unique aircraft registrations, API call Quota Usage will be high
Solution: Extract from df_flights data you already have!
```

###Make function to fetch Manufacturer
"""

# Function for manufacturer [add manufacturer if anything missing]
def get_manufacturer(model):
  if not isinstance(model, str) or not model.strip():
    return None

  first_word = model.strip().split()[0].lower()

  if first_word == 'airbus':
    return 'Airbus'
  elif first_word == 'boeing':
    return 'Boeing'
  elif first_word == 'atr':
    return 'ATR'
  elif first_word == 'embraer':
    return 'Embraer'
  elif first_word == 'bombardier':
    return 'Bombardier'
  elif first_word == 'bae':
    return 'BAe'
  elif first_word == 'mcdonnell':
    return 'McDonnell Douglas'
  elif first_word == 'ilyushin':
    return 'Ilyushin'
  elif first_word == 'cessna':
    return 'Cessna'
  elif first_word == 'canadair':
    return 'Canadair'
  elif first_word == 'de':
    return 'De Havilland'
  else:
    return None


tests = ['ATR 72', 'Airbus A320 NEO', 'Boeing 737 MAX 8', 'Bombardier Dash 8 Q400', 'De Havilland Canada DHC-8-400']
for model in tests:
    print(f"{model} -> {get_manufacturer(model)}")

"""###Make a clear Aircraft Dataframe

"""

aircraft_data = []
seen_registrations = set()

for idx, row in df_flights.iterrows():
  aircraft_reg = row['aircraft_reg']
  aircraft_model = row['aircraft_model']
  airline_name = row['airline_name']

  if aircraft_reg and aircraft_reg not in seen_registrations:
    seen_registrations.add(aircraft_reg)
    manufacturer = get_manufacturer(aircraft_model)
    aircraft_data.append((aircraft_reg, aircraft_model, manufacturer, airline_name))

df_aircraft = pd.DataFrame(aircraft_data, columns=['aircraft_reg', 'aircraft_model', 'manufacturer', 'airline_name'])
df_aircraft.head(10)

"""#PHASE 2: Database

##Create Database File - SQLite

 AIR TRACKER: Database Schema Design
"""

# Create SQLite Database

conn = sqlite3.connect('air_tracker.db')
cursor = conn.cursor()

print("Database created")

"""###Create Tables


```
AIRPORTS TABLE
FLIGHTS TABLE
AIRCRAFT TABLE
AIRPORT DELAYS
```


"""

#Airports Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS airports (
    airport_id INTEGER PRIMARY KEY AUTOINCREMENT,
    icao_code  TEXT UNIQUE,
    iata_code  TEXT UNIQUE NOT NULL,
    name       TEXT,
    city       TEXT,
    country    TEXT,
    continent  TEXT,
    latitude   REAL,
    longitude  REAL,
    timezone   TEXT
)
''')
print("Airports Table created")

#Aircrafts Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS aircraft (
    aircraft_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    aircraft_reg    TEXT UNIQUE NOT NULL,
    aircraft_model  TEXT,
    manufacturer    TEXT,
    airline_name    TEXT
)
''')
print("Aircrafts Table created")

#Flights Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS flights (
    flight_id        TEXT PRIMARY KEY,
    flight_number    TEXT,
    airline_code     TEXT,
    airline_name     TEXT,
    aircraft_reg     TEXT,
    aircraft_model   TEXT,
    origin_iata      TEXT,
    origin_icao      TEXT,
    dest_iata        TEXT,
    dest_icao        TEXT,
    scheduled_arr    TEXT,
    actual_arr       TEXT,
    delay_arr        REAL,
    scheduled_dep    TEXT,
    actual_dep       TEXT,
    delay_dep        REAL,
    status           TEXT,
    is_cargo         INTEGER,
    is_canceled      INTEGER,

    FOREIGN KEY (aircraft_reg) REFERENCES aircraft(aircraft_reg),
    FOREIGN KEY (origin_icao)  REFERENCES airports(icao_code),
    FOREIGN KEY (dest_icao)    REFERENCES airports(icao_code)
)
''')
print("Flights Table created")

#Airport Delays
cursor.execute('''
CREATE TABLE IF NOT EXISTS airport_delays (
    delay_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    airport_iata     TEXT,
    delay_date       TEXT,
    total_flights    INTEGER,
    delayed_flights  INTEGER,
    avg_delay_min    REAL,
    median_delay_min REAL,
    canceled_flights INTEGER,

    FOREIGN KEY (airport_iata) REFERENCES airports(iata_code)
)
''')
print("Airport Delays Table created")

conn.commit()
print("ALL TABLES CREATED SUCCESSFULLY")

"""###Verify Tables"""

cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = cursor.fetchall()
print("📋 Tables in database:")
for table in tables:
    print(f"   - {table[0]}")

"""## Insert Data to Database"""

# Airport data from df_airports
df_airports.to_sql('airports', conn, if_exists='replace', index=False)
print(f"Inserted {len(df_airports)} airports")

# Aircraft data from df_craft
df_aircraft.to_sql('aircraft', conn, if_exists='replace', index=False)
print(f"Inserted {len(df_aircraft)} aircrafts")

# Flights data from df_flights(df_flights_copy)
df_flight_copy = df_flights.copy()
df_flight_copy['is_cargo'] = df_flight_copy['is_cargo'].astype(int)
df_flight_copy['is_canceled'] = df_flight_copy['is_canceled'].astype(int)
df_flight_copy.to_sql('flights', conn, if_exists='replace', index=False)
print(f"Inserted {len(df_flights)} flights")

"""#PHASE 3: SQL queries

### 1) Show the total number of flights for each aircraft model, listing the model and its count.
"""

# Query 1: Show total number of flights for each aircraft model

query1 = """
SELECT
    a.aircraft_model,
    COUNT(f.flight_id) AS total_flights
FROM flights f
JOIN aircraft a ON f.aircraft_reg = a.aircraft_reg
GROUP BY a.aircraft_model
ORDER BY total_flights DESC
"""

result1 = run_query(
    1,
    "Total number of flights for each aircraft model",
    query1,
    show_rows=15
)

"""###2) List all aircraft (registration, model) that have been assigned to more than 5 flights."""

# Query 2: List aircraft with more than 5 flights

query2 = """
SELECT
    a.aircraft_reg AS registration,
    a.aircraft_model AS model,
    a.manufacturer,
    COUNT(f.flight_id) AS flight_count
FROM aircraft a
JOIN flights f ON a.aircraft_reg = f.aircraft_reg
GROUP BY a.aircraft_reg, a.aircraft_model, a.manufacturer
HAVING COUNT(f.flight_id) > 5
ORDER BY flight_count DESC
"""

result2 = run_query(
    2,
    "Aircraft with more than 5 flights",
    query2,
    show_rows=15
)

"""###3) For each airport, display its name and the number of outbound flights, but only for airports with more than 5 flights."""

# Query 3: Airports with more than 5 outbound flights

query3 = """
SELECT
    ap.name AS airport_name,
    ap.city,
    ap.country,
    COUNT(f.flight_id) AS outbound_flights
FROM airports ap
JOIN flights f ON ap.icao_code = f.origin_icao
GROUP BY ap.icao_code, ap.name, ap.city, ap.country
HAVING COUNT(f.flight_id) > 5
ORDER BY outbound_flights DESC
"""

result3 = run_query(
    3,
    "Airports with more than 5 outbound flights",
    query3
)

"""###4) Find the top 3 destination airports (name, city) by number of arriving flights, sorted by count descending."""

# Query 4: Top 3 destination airports by arriving flights

query4 = """
SELECT
    ap.name AS airport_name,
    ap.city,
    ap.country,
    COUNT(f.flight_id) AS arriving_flights
FROM airports ap
JOIN flights f ON ap.icao_code = f.dest_icao
GROUP BY ap.icao_code, ap.name, ap.city, ap.country
ORDER BY arriving_flights DESC
LIMIT 3
"""

result4 = run_query(
    4,
    "Top 3 destination airports by number of arriving flights",
    query4
)

"""###5) Show for each flight: number, origin, destination, and a label 'Domestic' or 'International' using CASE WHEN on country match."""

# Query 5: Label flights as Domestic or International

query5 = """
SELECT
    f.flight_number,
    origin.iata_code AS origin,
    origin.country AS origin_country,
    dest.iata_code AS destination,
    dest.country AS dest_country,
    CASE
        WHEN origin.country = dest.country THEN 'Domestic'
        ELSE 'International'
    END AS flight_type
FROM flights f
LEFT JOIN airports origin ON f.origin_icao = origin.icao_code
LEFT JOIN airports dest ON f.dest_icao = dest.icao_code
WHERE origin.icao_code IS NOT NULL
   OR dest.icao_code IS NOT NULL
LIMIT 20
"""

result5 = run_query(
    5,
    "Flights labeled as Domestic or International",
    query5,
    show_rows=20
)

# Summary statistics
print("Summary:")
if result5 is not None:
    summary = result5['flight_type'].value_counts()
    print(tabulate(summary.reset_index(),
                   headers=['Flight Type', 'Count'],
                   tablefmt='grid',
                   showindex=False))

"""###6) Show the 5 most recent arrivals at “DEL” airport including flight number, aircraft, departure airport name, and arrival time, ordered by latest arrival."""

# Query 6: 5 most recent arrivals at DEL airport

query6 = """
SELECT
    f.flight_number,
    a.aircraft_model AS aircraft,
    a.manufacturer,
    origin.name AS departure_airport,
    origin.city AS departure_city,
    f.actual_arr AS arrival_time,
    f.status
FROM flights f
LEFT JOIN aircraft a ON f.aircraft_reg = a.aircraft_reg
LEFT JOIN airports origin ON f.origin_icao = origin.icao_code
LEFT JOIN airports dest ON f.dest_icao = dest.icao_code
WHERE dest.iata_code = 'DEL'
ORDER BY f.scheduled_arr DESC
LIMIT 5
"""

result6 = run_query(
    6,
    "5 most recent arrivals at DEL airport",
    query6
)

"""###7) Find all airports with no arriving flights (never used as a destination in flights table)."""

# Query 7: Airports with no arriving flights

query7 = """
SELECT
    ap.iata_code,
    ap.name AS airport_name,
    ap.city,
    ap.country
FROM airports ap
LEFT JOIN flights f ON ap.icao_code = f.dest_icao
WHERE f.flight_id IS NULL
ORDER BY ap.name
"""

result7 = run_query(
    7,
    "Airports with no arriving flights (never used as destination)",
    query7
)

"""###8) For each airline, count the number of fl ights by status (e.g., 'On Time', 'Delayed', 'Cancelled') using CASE WHEN."""

# Query 8: Count flights by status for each airline

query8 = """
SELECT
    f.airline_name,
    SUM(CASE WHEN f.status = 'Arrived' THEN 1 ELSE 0 END) AS arrived,
    SUM(CASE WHEN f.status = 'Departed' THEN 1 ELSE 0 END) AS departed,
    SUM(CASE WHEN f.status = 'Unknown' THEN 1 ELSE 0 END) AS unknown,
    SUM(CASE WHEN f.status = 'Expected' THEN 1 ELSE 0 END) AS expected,
    SUM(CASE WHEN f.status = 'Approaching' THEN 1 ELSE 0 END) AS approaching,
    SUM(CASE WHEN f.status = 'Canceled' THEN 1 ELSE 0 END) AS canceled,
    SUM(CASE WHEN f.status = 'Delayed' THEN 1 ELSE 0 END) AS delayed,
    COUNT(f.flight_id) AS total_flights
FROM flights f
GROUP BY f.airline_name
ORDER BY total_flights DESC
"""

result8 = run_query(
    8,
    "Flight count by status for each airline",
    query8,
    show_rows=15
)

"""###9) Show all cancelled flights, with aircraft and both airports, ordered by departure time descending."""

# Query 9: Show all cancelled flights with details

query9 = """
SELECT
    f.flight_number,
    f.airline_name,
    dest.name AS destination_airport,
    dest.city AS destination_city,
    f.scheduled_dep AS scheduled_departure,
    f.status
FROM flights f
LEFT JOIN aircraft a ON f.aircraft_reg = a.aircraft_reg
LEFT JOIN airports origin ON f.origin_icao = origin.icao_code
LEFT JOIN airports dest ON f.dest_icao = dest.icao_code
WHERE f.status = 'Canceled'
ORDER BY f.scheduled_dep DESC NULLS LAST
"""

result9 = run_query(
    9,
    "All cancelled flights with aircraft and airport details",
    query9,
    show_rows=15
)

"""###10) List all city pairs (origin-destination) that have more than 2 different aircraft models operating flights between them."""

# Query 10: City pairs with more than 2 different aircraft models

query10 = """
SELECT
    origin.city AS origin_city,
    dest.city AS dest_city,
    origin.iata_code AS origin_code,
    dest.iata_code AS dest_code,
    COUNT(DISTINCT a.aircraft_model) AS aircraft_model_count,
    GROUP_CONCAT(DISTINCT a.aircraft_model) AS aircraft_models
FROM flights f
LEFT JOIN airports origin ON f.origin_icao = origin.icao_code
LEFT JOIN airports dest ON f.dest_icao = dest.icao_code
LEFT JOIN aircraft a ON f.aircraft_reg = a.aircraft_reg
GROUP BY origin.city, dest.city, origin.iata_code, dest.iata_code
HAVING COUNT(DISTINCT a.aircraft_model) > 2
ORDER BY aircraft_model_count DESC
LIMIT 20
"""

result10 = run_query(
    10,
    "City pairs with more than 2 different aircraft models",
    query10,
    show_rows=15
)

"""###11) For each destination airport, compute the % of delayed flights (status='Delayed') among all arrivals, sorted by highest percentage."""

# Query 11: % of delayed flights for each destination airport

query11 = """
SELECT
    ap.name AS airport_name,
    ap.city,
    ap.iata_code,
    COUNT(f.flight_id) AS total_arrivals,
    SUM(CASE WHEN f.status = 'Delayed' OR f.delay_arr > 0 THEN 1 ELSE 0 END) AS delayed_arrivals,
    ROUND(
        (SUM(CASE WHEN f.status = 'Delayed' OR f.delay_arr > 0 THEN 1 ELSE 0 END) * 100.0) /
        COUNT(f.flight_id),
        2
    ) AS delay_percentage
FROM airports ap
JOIN flights f ON ap.icao_code = f.dest_icao
GROUP BY ap.icao_code, ap.name, ap.city, ap.iata_code
HAVING COUNT(f.flight_id) > 0
ORDER BY delay_percentage DESC
"""

result11 = run_query(
    11,
    "Percentage of delayed flights by destination airport",
    query11
)

"""#PHASE 4: STREAMLIT"""
import streamlit as st
import sqlite3
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

# ============================================================================
# 🔧 CONFIGURATION
# ============================================================================

st.set_page_config(
    page_title="Air Tracker - Flight Analytics",
    page_icon="✈️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================================
# 🗄️ DATABASE CONNECTION
# ============================================================================

@st.cache_resource
def get_connection():
    """Create database connection"""
    return sqlite3.connect('air_tracker.db', check_same_thread=False)

def get_data(query, params=None):
    """Execute SQL query and return DataFrame"""
    conn = get_connection()
    if params:
        df = pd.read_sql_query(query, conn, params=params)
    else:
        df = pd.read_sql_query(query, conn)
    return df

# ============================================================================
# 🎨 CUSTOM CSS STYLING
# ============================================================================

st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        font-weight: bold;
        text-align: center;
        color: #1E88E5;
        padding: 1rem;
    }
    .sub-header {
        font-size: 1.5rem;
        color: #424242;
        text-align: center;
        margin-bottom: 2rem;
    }
    .metric-card {
        background-color: #f0f2f6;
        padding: 1rem;
        border-radius: 0.5rem;
        border-left: 5px solid #1E88E5;
    }
    .stTabs [data-baseweb="tab-list"] {
        gap: 2rem;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================================
# 📊 SIDEBAR NAVIGATION
# ============================================================================

st.sidebar.title("🛩️ Navigation")
st.sidebar.markdown("---")

page = st.sidebar.radio(
    "Go to:",
    ["🏠 Home Dashboard", 
     "✈️ Flight Explorer", 
     "🛩️ Aircraft Analytics",
     "🏢 Airport Location",
     "⏰ Delay Insights",
     "📊 SQL Query Results",
     "👨‍💻 About Project"]
)

st.sidebar.markdown("---")
st.sidebar.info("""
**Air Tracker v1.0**  
GUVI Project  
Aviation Data Analytics  
""")

# ============================================================================
# 🏠 PAGE 1: HOME DASHBOARD
# ============================================================================

if page == "🏠 Home Dashboard":
    st.markdown('<div class="main-header">✈️ AIR TRACKER: Flight Analytics</div>', 
                unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Real-time Aviation Data Insights</div>', 
                unsafe_allow_html=True)
    
    # Summary Statistics
    col1, col2, col3, col4 = st.columns(4)
    
    total_flights = get_data("SELECT COUNT(*) as count FROM flights")['count'][0]
    total_aircraft = get_data("SELECT COUNT(*) as count FROM aircraft")['count'][0]
    total_airports = get_data("SELECT COUNT(*) as count FROM airports")['count'][0]
    total_airlines = get_data("SELECT COUNT(DISTINCT airline_name) as count FROM flights")['count'][0]
    
    col1.metric("✈️ Total Flights", f"{total_flights:,}")
    col2.metric("🛩️ Aircraft", f"{total_aircraft:,}")
    col3.metric("🏢 Airports", f"{total_airports}")
    col4.metric("🏢 Airlines", f"{total_airlines}")
    
    st.markdown("---")
    
    # Key Insights in 2 columns
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("📊 Flight Status Distribution")
        status_data = get_data("""
            SELECT status, COUNT(*) as count 
            FROM flights 
            GROUP BY status 
            ORDER BY count DESC
        """)
        fig = px.pie(status_data, values='count', names='status', 
                     title='Flight Status Breakdown',
                     color_discrete_sequence=px.colors.qualitative.Set3)
        st.plotly_chart(fig, use_container_width=True)
    
    with col2:
        st.subheader("🏢 Top 5 Airlines by Flight Count")
        airline_data = get_data("""
            SELECT airline_name, COUNT(*) as flight_count 
            FROM flights 
            GROUP BY airline_name 
            ORDER BY flight_count DESC 
            LIMIT 5
        """)
        fig = px.bar(airline_data, x='airline_name', y='flight_count',
                     title='Busiest Airlines',
                     labels={'airline_name': 'Airline', 'flight_count': 'Flights'},
                     color='flight_count',
                     color_continuous_scale='Blues')
        st.plotly_chart(fig, use_container_width=True)
        
# ============================================================================
# ✈️ PAGE 2: FLIGHT EXPLORER
# ============================================================================

elif page == "✈️ Flight Explorer":
    st.title("✈️ Flight Explorer")
    st.markdown("Search and filter flights with detailed information")

    # Filters
    col1, col2, col3 = st.columns(3)

    with col1:
        airlines = get_data(
            "SELECT DISTINCT airline_name FROM flights ORDER BY airline_name"
        )["airline_name"].tolist()
        selected_airline = st.selectbox("Select Airline", ["All"] + airlines)

    with col2:
        statuses = get_data(
            "SELECT DISTINCT status FROM flights ORDER BY status"
        )["status"].tolist()
        selected_status = st.selectbox("Select Status", ["All"] + statuses)

    with col3:
        airports = get_data(
            "SELECT DISTINCT iata_code FROM airports ORDER BY iata_code"
        )["iata_code"].tolist()
        selected_origin = st.selectbox("Origin Airport", ["All"] + airports)

    # ------------------ BASE QUERY (for metrics: NO status filter) ------------------
    base_query = """
        SELECT
            f.flight_number,
            f.airline_name,
            origin.iata_code AS origin,
            origin.city      AS origin_city,
            f.scheduled_dep,
            f.status
        FROM flights f
        JOIN airports origin ON f.origin_icao = origin.icao_code
        WHERE 1 = 1
    """

    base_params = []
    if selected_airline != "All":
        base_query += " AND f.airline_name = ?"
        base_params.append(selected_airline)
    if selected_origin != "All":
        base_query += " AND origin.iata_code = ?"
        base_params.append(selected_origin)

    # full set for this airline/origin, all statuses
    base_df = get_data(base_query, tuple(base_params) if base_params else None)

    # ------------------ TABLE QUERY (optional extra status filter) ------------------
    table_query = base_query      # start from same query text
    table_params = list(base_params)

    if selected_status != "All":
        table_query += " AND f.status = ?"
        table_params.append(selected_status)

    table_query += " ORDER BY f.scheduled_dep DESC LIMIT 1000"
    flights_df = get_data(table_query, tuple(table_params) if table_params else None)

    st.subheader(f"📋 Showing {len(flights_df)} flights")
    st.dataframe(flights_df, use_container_width=True, height=400)

    # ------------------ CANCELLATION METRICS (always from base_df) ------------------
    total_flights = len(base_df)

    if total_flights > 0 and "status" in base_df.columns:
        canceled_count = (base_df["status"] == "Canceled").sum()
        canceled_pct = (canceled_count / total_flights) * 100

        m1, m2, m3 = st.columns(3)
        m1.metric("Total Flights", total_flights)
        m2.metric("Canceled Flights", int(canceled_count))
        m3.metric("Canceled %", f"{canceled_pct:.1f}%")
    else:
        m1, m2, m3 = st.columns(3)
        m1.metric("Total Flights", 0)
        m2.metric("Canceled Flights", 0)
        m3.metric("Canceled %", "0.0%")



# ============================================================================
# 🛩️ PAGE 3: AIRCRAFT ANALYTICS
# ============================================================================

elif page == "🛩️ Aircraft Analytics":
    st.title("🛩️ Aircraft Analytics")
    
    # Top Aircraft Models
    st.subheader("📊 Top 10 Aircraft Models by Flight Count")
    aircraft_stats = get_data("""
        SELECT 
            a.aircraft_model,
            a.manufacturer,
            COUNT(f.flight_id) as flight_count,
            COUNT(DISTINCT f.airline_name) as airlines_using
        FROM aircraft a
        JOIN flights f ON a.aircraft_reg = f.aircraft_reg
        GROUP BY a.aircraft_model, a.manufacturer
        ORDER BY flight_count DESC
        LIMIT 10
    """)
    
    fig = px.bar(aircraft_stats, x='aircraft_model', y='flight_count',
                 color='manufacturer',
                 title='Most Used Aircraft Models',
                 labels={'aircraft_model': 'Aircraft Model', 'flight_count': 'Number of Flights'},
                 text='flight_count')
    fig.update_traces(texttemplate='%{text}', textposition='outside')
    st.plotly_chart(fig, use_container_width=True)
    
    # Detailed Table
    st.subheader("📋 Aircraft Fleet Details")
    st.dataframe(aircraft_stats, use_container_width=True)
    
    # Manufacturer Distribution
    st.subheader("🏭 Manufacturer Distribution")
    mfr_data = get_data("""
        SELECT manufacturer, COUNT(*) as aircraft_count
        FROM aircraft
        GROUP BY manufacturer
        ORDER BY aircraft_count DESC
    """)
    
    fig = px.pie(mfr_data, values='aircraft_count', names='manufacturer',
                 title='Aircraft by Manufacturer')
    st.plotly_chart(fig, use_container_width=True)

# ============================================================================
# 🏢 PAGE 4: AIRPORT LOCATION
# ============================================================================

elif page == "🏢 Airport Location":
    st.title("🏢 Airport Location")
    
    # Airport selector
    airports = get_data("SELECT iata_code, name, city FROM airports ORDER BY name")
    selected_airport = st.selectbox(
        "Select Airport",
        airports['iata_code'].tolist(),
        format_func=lambda x: f"{x} - {airports[airports['iata_code']==x]['name'].values[0]}"
    )
    
    # Airport Details
    airport_info = get_data(
        "SELECT * FROM airports WHERE iata_code = ?",
        (selected_airport,)
    )
    
    if not airport_info.empty:
        st.subheader(f"📍 {airport_info['name'].values[0]}")
        col1, col2, col3 = st.columns(3)
        col1.metric("City", airport_info['city'].values[0])
        col2.metric("Country", airport_info['country'].values[0])
        col3.metric("Timezone", airport_info['timezone'].values[0])
        
        # Map
        st.subheader("🗺️ Location")
        map_data = pd.DataFrame({
            'lat': [airport_info['latitude'].values[0]],
            'lon': [airport_info['longitude'].values[0]]
        })
        st.map(map_data, zoom=10)
 
# ============================================================================
# ⏰ PAGE 5: DELAY INSIGHTS
# ============================================================================

elif page == "⏰ Delay Insights":
    st.title("⏰ Delay Insights")
    
    # Delay Statistics
    st.subheader("📊 Delay Overview")
    
    delay_stats = get_data("""
        SELECT 
            COUNT(*) as total_flights,
            SUM(CASE WHEN delay_dep > 0 THEN 1 ELSE 0 END) as delayed_flights,
            ROUND(AVG(CASE WHEN delay_dep > 0 THEN delay_dep END), 2) as avg_delay,
            MAX(delay_dep) as max_delay
        FROM flights
    """)
    
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Flights", f"{delay_stats['total_flights'].values[0]:,}")
    col2.metric("Delayed Flights", f"{delay_stats['delayed_flights'].values[0]:,}")
    col3.metric("Avg Delay (min)", f"{delay_stats['avg_delay'].values[0]:.1f}")
    col4.metric("Max Delay (min)", f"{delay_stats['max_delay'].values[0]:.0f}")
    
    # Delay by Airport
    st.subheader("🏢 Delays by Airport")
    airport_delays = get_data("""
        SELECT 
            ap.name AS airport_name,
            ap.iata_code,
            COUNT(f.flight_id) as total_flights,
            SUM(CASE WHEN f.delay_dep > 0 THEN 1 ELSE 0 END) as delayed_flights,
            ROUND(AVG(CASE WHEN f.delay_dep > 0 THEN f.delay_dep END), 2) as avg_delay,
            ROUND((SUM(CASE WHEN f.delay_dep > 0 THEN 1 ELSE 0 END) * 100.0) / COUNT(f.flight_id), 2) as delay_percentage
        FROM airports ap
        JOIN flights f ON ap.icao_code = f.origin_icao
        GROUP BY ap.name, ap.iata_code
        HAVING total_flights > 10
        ORDER BY delay_percentage DESC
    """)
    
    fig = px.bar(airport_delays, x='iata_code', y='delay_percentage',
                 title='Delay Percentage by Airport',
                 labels={'iata_code': 'Airport', 'delay_percentage': 'Delay %'},
                 hover_data=['airport_name', 'total_flights', 'avg_delay'])
    st.plotly_chart(fig, use_container_width=True)
    
    # Detailed Table
    st.subheader("📋 Detailed Delay Statistics")
    st.dataframe(airport_delays, use_container_width=True)

# ============================================================================
# 📊 PAGE 6: SQL QUERY RESULTS
# ============================================================================

elif page == "📊 SQL Query Results":
    st.title("📊 SQL Query Results")
    st.markdown("View results of all 11 GUVI required queries")
    
    query_options = {
                "1) Flights per Aircraft Model": """
            SELECT 
                a.aircraft_model,
                COUNT(f.flight_id) AS total_flights
            FROM flights f
            JOIN aircraft a ON f.aircraft_reg = a.aircraft_reg
            GROUP BY a.aircraft_model
            ORDER BY total_flights DESC
        """,
        "2) Aircraft with > 5 Flights": """
            SELECT 
                a.aircraft_reg   AS registration,
                a.aircraft_model AS model,
                a.manufacturer,
                COUNT(f.flight_id) AS flight_count
            FROM aircraft a
            JOIN flights f ON a.aircraft_reg = f.aircraft_reg
            GROUP BY a.aircraft_reg, a.aircraft_model, a.manufacturer
            HAVING COUNT(f.flight_id) > 5
            ORDER BY flight_count DESC
        """,
        "3) Airports with > 5 Outbound Flights": """
            SELECT 
                ap.name AS airport_name,
                ap.city,
                ap.country,
                COUNT(f.flight_id) AS outbound_flights
            FROM airports ap
            JOIN flights f ON ap.icao_code = f.origin_icao
            GROUP BY ap.icao_code, ap.name, ap.city, ap.country
            HAVING COUNT(f.flight_id) > 5
            ORDER BY outbound_flights DESC
        """,
        "4) Top 3 Destination Airports": """
            SELECT 
                ap.name AS airport_name,
                ap.city,
                ap.country,
                COUNT(f.flight_id) AS arriving_flights
            FROM airports ap
            JOIN flights f ON ap.icao_code = f.dest_icao
            GROUP BY ap.icao_code, ap.name, ap.city, ap.country
            ORDER BY arriving_flights DESC
            LIMIT 3
        """,
        "5) Domestic vs International (Per Flight)": """
            SELECT 
                f.flight_number,
                origin.iata_code AS origin,
                origin.country   AS origin_country,
                dest.iata_code   AS destination,
                dest.country     AS dest_country,
                CASE 
                    WHEN origin.country = dest.country THEN 'Domestic'
                    ELSE 'International'
                END AS flight_type
            FROM flights f
            LEFT JOIN airports origin ON f.origin_icao = origin.icao_code
            LEFT JOIN airports dest   ON f.dest_icao   = dest.icao_code
            WHERE origin.icao_code IS NOT NULL
               OR dest.icao_code   IS NOT NULL
            LIMIT 200
        """,
        "6) 5 Most Recent Arrivals at DEL": """
            SELECT 
                f.flight_number,
                a.aircraft_model AS aircraft,
                a.manufacturer,
                origin.name AS departure_airport,
                origin.city AS departure_city,
                f.actual_arr AS arrival_time,
                f.status
            FROM flights f
            LEFT JOIN aircraft a ON f.aircraft_reg = a.aircraft_reg
            LEFT JOIN airports origin ON f.origin_icao = origin.icao_code
            LEFT JOIN airports dest   ON f.dest_icao   = dest.icao_code
            WHERE dest.iata_code = 'DEL'
            ORDER BY f.scheduled_arr DESC
            LIMIT 5
        """,
        "7) Airports with No Arriving Flights": """
            SELECT 
                ap.iata_code,
                ap.name   AS airport_name,
                ap.city,
                ap.country
            FROM airports ap
            LEFT JOIN flights f ON ap.icao_code = f.dest_icao
            WHERE f.flight_id IS NULL
            ORDER BY ap.name
        """,
        "8) Flights by Status per Airline": """
            SELECT 
                f.airline_name,
                SUM(CASE WHEN f.status = 'Arrived'     THEN 1 ELSE 0 END) AS arrived,
                SUM(CASE WHEN f.status = 'Departed'    THEN 1 ELSE 0 END) AS departed,
                SUM(CASE WHEN f.status = 'Unknown'     THEN 1 ELSE 0 END) AS unknown,
                SUM(CASE WHEN f.status = 'Expected'    THEN 1 ELSE 0 END) AS expected,
                SUM(CASE WHEN f.status = 'Approaching' THEN 1 ELSE 0 END) AS approaching,
                SUM(CASE WHEN f.status = 'Canceled'    THEN 1 ELSE 0 END) AS canceled,
                SUM(CASE WHEN f.status = 'Delayed'     THEN 1 ELSE 0 END) AS delayed,
                COUNT(f.flight_id) AS total_flights
            FROM flights f
            GROUP BY f.airline_name
            ORDER BY total_flights DESC
        """,
        "9) All Cancelled Flights": """
            SELECT 
                f.flight_number,
                f.airline_name,
                dest.name AS destination_airport,
                dest.city AS destination_city,
                f.scheduled_dep AS scheduled_departure,
                f.status
            FROM flights f
            LEFT JOIN aircraft a ON f.aircraft_reg = a.aircraft_reg
            LEFT JOIN airports origin ON f.origin_icao = origin.icao_code
            LEFT JOIN airports dest   ON f.dest_icao   = dest.icao_code
            WHERE f.status = 'Canceled'
            ORDER BY f.scheduled_dep DESC NULLS LAST
        """,
        "10) City Pairs with > 2 Aircraft Models": """
            SELECT 
                origin.city AS origin_city,
                dest.city   AS dest_city,
                origin.iata_code AS origin_code,
                dest.iata_code   AS dest_code,
                COUNT(DISTINCT a.aircraft_model) AS aircraft_model_count,
                GROUP_CONCAT(DISTINCT a.aircraft_model) AS aircraft_models
            FROM flights f
            LEFT JOIN airports origin ON f.origin_icao = origin.icao_code
            LEFT JOIN airports dest   ON f.dest_icao   = dest.icao_code
            LEFT JOIN aircraft a      ON f.aircraft_reg = a.aircraft_reg
            GROUP BY origin.city, dest.city, origin.iata_code, dest.iata_code
            HAVING COUNT(DISTINCT a.aircraft_model) > 2
            ORDER BY aircraft_model_count DESC
            LIMIT 20
        """,
        "11) % Delayed Arrivals per Destination": """
            SELECT 
                ap.name AS airport_name,
                ap.city,
                ap.iata_code,
                COUNT(f.flight_id) AS total_arrivals,
                SUM(CASE WHEN f.status = 'Delayed' OR f.delay_arr > 0 THEN 1 ELSE 0 END)
                    AS delayed_arrivals,
                ROUND(
                    (SUM(CASE WHEN f.status = 'Delayed' OR f.delay_arr > 0 THEN 1 ELSE 0 END)
                    * 100.0) / COUNT(f.flight_id),
                    2
                ) AS delay_percentage
            FROM airports ap
            JOIN flights f ON ap.icao_code = f.dest_icao
            GROUP BY ap.icao_code, ap.name, ap.city, ap.iata_code
            HAVING COUNT(f.flight_id) > 0
            ORDER BY delay_percentage DESC
        """,
    }
    
    selected_query = st.selectbox("Select Query", list(query_options.keys()))
    
    if st.button("Execute Query"):
        with st.spinner("Executing query..."):
            result = get_data(query_options[selected_query])
            st.success(f"Query returned {len(result)} rows")
            st.dataframe(result, use_container_width=True)
            
            # Download option
            csv = result.to_csv(index=False)
            st.download_button(
                label="📥 Download as CSV",
                data=csv,
                file_name=f"{selected_query.replace(' ', '_')}.csv",
                mime="text/csv"
            )

# ============================================================================
# 👨‍💻 PAGE 7: ABOUT PROJECT
# ============================================================================

elif page == "👨‍💻 About Project":
    st.title("👨‍💻 About This Project")
    
    st.markdown("""
    ## 🎯 Air Tracker: Flight Analytics
    ### 📌 Project Overview
    **GUVI Project**  
    **Domain:** Aviation / Data Analytics
    
    ### 📊 Database Schema
    - **airports:** 12 major airports
    - **aircraft:** 2,370+ aircraft records
    - **flights:** 32,824+ flight records
        
    ### 👨‍💻 Developer Information
    **Created by:** [Rajaguru]
    
    ### 📚 Project Structure
```
    air-tracker/
    ├── app.py                 # Streamlit application
    ├── air_tracker.db        # SQLite database
    ├── data_collection.ipynb # API data extraction
    ├── requirements.txt      # Dependencies
    └── README.md            # Documentation
```
    """)
